Input:
- Startzeitpunkt
- Endzeitpunkt
- Prediction Data


Output:
- Observations für den Zeitraum Start - Ende
- Serial Interval der Länge des Zeitraums (Start - Ende)
- Prediction Data für den Zeitraum Start - Ende
- Initialisierte Parameter des Models (ggf. mit entsprechendem Zeitraum)

In [11]:
import pandas as pd
import numpy as np
from datetime import date

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Initialization

## Initialize Observations

In [50]:
def initialize_observations(filename='observations_03022022.csv', start='2020-02-26', end='2022-01-31', observations=['Number_of_deaths', 'Confirmed_cases', 'Admissions_hospital']):
  filename_obs = r'/content/drive/MyDrive/GitHub/master-thesis/data/' + filename
  df_obs = pd.read_csv(filename_obs, sep=';', thousands='.', decimal=',', encoding='utf-8', parse_dates=['Date'])
  time_period = (df_obs['Date'] >= start) & (df_obs['Date'] < end)
  columns = ['Date'] + observations
  df_obs_filtered = df_obs.loc[time_period][columns].reset_index(drop=True)
  return df_obs_filtered

In [51]:
initialize_observations()

          Date  Number_of_deaths  Confirmed_cases  Admissions_hospital
0   2020-02-26                 0                1                    0
1   2020-02-27                 0                1                    0
2   2020-02-28                 0                1                    0
3   2020-03-01                 0                1                    1
4   2020-03-02                 0                4                    0
..         ...               ...              ...                  ...
699 2022-01-26                19            41724                  279
700 2022-01-27                16            39088                  290
701 2022-01-28                18            35946                  250
702 2022-01-29                16            28186                  218
703 2022-01-30                11            12808                  195

[704 rows x 4 columns]

## Initialize Serial Interval & Delay Distribution

In [72]:
df_si_dd = pd.read_csv('/content/drive/MyDrive/GitHub/master-thesis/data/serial_interval_and_delay_distribution_covidmodel.csv', sep=';', decimal=',', encoding='utf-8', dtype={'serial_interval': np.float64, 'delay_distr': np.float64})
df_si_dd

ValueError: ignored

In [70]:
df_si_dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   t                407 non-null    object
 1   serial_interval  407 non-null    object
 2   delay_distr      407 non-null    object
dtypes: object(3)
memory usage: 9.7+ KB

## Initialize Model Parameter

## Initialize Prediction Data

# Initialize Model

In [58]:
def initialize_model(start='2020-02-28', end='2022-01-31', pred_data='', observations=['Number_of_deaths', 'Confirmed_cases', 'Admissions_hospital']):
  df_observations = initialize_observations(start=start, end=end, observations=observations)

  return df_observations

In [61]:
initialize_model()

          Date  Number_of_deaths  Confirmed_cases  Admissions_hospital
0   2020-02-28                 0                1                    0
1   2020-03-01                 0                1                    1
2   2020-03-02                 0                4                    0
3   2020-03-03                 0                4                    1
4   2020-03-04                 0                3                    0
..         ...               ...              ...                  ...
697 2022-01-26                19            41724                  279
698 2022-01-27                16            39088                  290
699 2022-01-28                18            35946                  250
700 2022-01-29                16            28186                  218
701 2022-01-30                11            12808                  195

[702 rows x 4 columns]